Начал задание
htmlacademy-php/517275-yeticave-12 pull request #11
Opened 2020-08-07 19:49 UTC by kingOfSauce

2020-08-08 02:23 UTC, b1rdex requested changes

2020-08-08 02:23 UTC, b1rdex commented on templates/main.php
> +                    <h3 class="lot__title"><a class="text-link" href="../../lot.php?id=<?=$lot['id']?>"><?=htmlspecialchars($lot['title']); ?></a></h3>
Почему такой путь `../../lot.php`? Он же в одной папке с index.php

2020-08-08 02:23 UTC, b1rdex commented on lot.php
> +  function count_date ($exp_date) {
Вынеси эти функции в отдельный файл и подключай его в index.php и lot.php, чтобы не дублировать их.

2020-08-08 02:23 UTC, b1rdex commented on lot.php
> +  $id = $_GET['id'];
Тут нужно проверить, что в $_GET вообще есть ключ id. Т.к. если его там не будет, эта строка выбросит ошибку. Используй isset() или null coalescing.

2020-08-08 02:23 UTC, b1rdex commented on lot.php
> +  if(in_array($id, $_GET) == false) {
Проверка неправильная. Этот код проверяет находится ли значение переменной $id в $_GET.

2020-08-08 02:23 UTC, b1rdex commented on lot.php
> +    echo "Ошибка ".http_response_code();
Лучше написать «лот не найден»

2020-08-08 02:23 UTC, b1rdex commented on lot.php
> +$lot = get_lot($con);
Тут нужно ещё раз проверить, что лот нашёлся в бд, т.к. наличие id в адресной строке не означает, что такой лот есть в бд. Если его тут нет, то выбросить 404.

2020-08-08 18:53 UTC, kingOfSauce commented on templates/main.php
> +                    <h3 class="lot__title"><a class="text-link" href="../../lot.php?id=<?=$lot['id']?>"><?=htmlspecialchars($lot['title']); ?></a></h3>
Такой путь, потому что это относительная ссылка из файла main.php на lot.php, который находится на уровень выше

2020-08-10 03:46 UTC, b1rdex requested changes

2020-08-10 03:46 UTC, b1rdex commented on lot.php
> +if (count($lot) == 0) {
if (null === $lot)

2020-08-10 03:46 UTC, b1rdex commented on lot.php
> +    $lots_sql = "SELECT l.id, title, img, c.name, expiration_date, description, bet_step, price FROM lot l JOIN category c ON l.category_id = c.id JOIN bet b ON l.id = b.lot_id WHERE l.id = ".$id;
`l.id = ".$id`
У тебя тут sql инъекция. Данные нужно передавать через третий параметр db_get_prepare_stmt

2020-08-10 03:46 UTC, b1rdex commented on templates/lot-layout.php
> +<!DOCTYPE html>
Разве layout отличается? Вроде там он одинаковый на всех страницах.

2020-08-10 03:46 UTC, b1rdex commented on templates/main.php
> +                    <h3 class="lot__title"><a class="text-link" href="../../lot.php?id=<?=$lot['id']?>"><?=htmlspecialchars($lot['title']); ?></a></h3>
Путь неправильный. Ссылка в html и расположение файлов php не связаны, т.к. у тебя всё отдаётся на странице `/index.php` и `/` является корнем. Тут должно быть `href="lot.php?id=`, это касается всех ссылок.

2020-08-10 03:46 UTC, b1rdex commented on templates/lot-main.php
> +<h2><?=$lot['title']?></h2>
Это можно переименовать просто в lot.php

2020-08-10 17:25 UTC, kingOfSauce commented on templates/lot-layout.php
> +<!DOCTYPE html>
я сделал этот layout из файла pages/lot.html

2020-08-10 17:29 UTC, kingOfSauce commented on templates/lot-main.php
> +<h2><?=$lot['title']?></h2>
Так уже ведь есть файл с таким названием

2020-08-12 02:56 UTC, b1rdex commented on templates/lot-main.php
> +<h2><?=$lot['title']?></h2>
В папке templates Нет

2020-08-12 02:57 UTC, b1rdex requested changes

2020-08-12 02:57 UTC, b1rdex commented on templates/lot-layout.php
> +<!DOCTYPE html>
Проверь, они же одинаковые с main. Если одинаковые, то надо удалять и переделывать на main

2020-08-13 09:40 UTC, b1rdex commented on index.php
```suggestion
```

2020-08-13 09:41 UTC, b1rdex approved these changes

2020-08-13 09:42 UTC, merged